# Generated by Django 4.0.2 on 2022-02-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(default=False, max_length=2003),
        ),
    ]
