# Generated by Django 4.0.2 on 2022-02-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_book_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
